version: "3.9"

services:
    server:
        build: ./docker/server
        ports:
            - "30120:30120/tcp"
            - "30120:30120/udp"
            - "40120:40120"
        volumes:
            - ./server:/var/server
        command: bash -c "/bin/sh -c /usr/local/bin/init.sh && tail -f /dev/null"